//! Examplary contract showcasing basic building blocks of writing smart
//! contracts in ink!.
//!
//! The "Bulletin Board" smart contract's functionality allows for posting short
//! texts to chain, one per user. Later, the posts can be deleted, but only by
//! its authors.
//!
//! In the constructor of the contract we're instantiating an instance of
//! "Highlighted Posts board". Note that this will work only if the `code_hash`,
//! supplied as an argument to the constructor, indeed refers to the expected
//! contract - otherwise the calls to `highlight_post` and `delete_highlight`
//! will fail as the receiving contract will not have the expected endpoint.

#![cfg_attr(not(feature = "std"), no_std, no_main)]

// An entrypoint to all ink! smart contracts.
// When expanded, this macro will:
// * Add local type aliases to the `mod bulletin_board`, like `Environment`,
//   `AccountId`, `Balance`, `Hash`, `Timestamp` and `BlockNumber`. All will
//   resolve to defaults `ink::env::DefaultEnvironment::<type>`
// * Adds useful #[doc] macros
// * various attributes to structs and functions
// * and many others.
// For complete breakdown, one can use _expand macro recursively_ feature in
// one's favorite IDE.
//
// It enforces various invariants of the contract, including (but not limited
// to):
// * exactly one `#[ink(storage)]`
// * at least one `#[ink(constructor)]`
// * at least one `#[ink(message)]`
// * and few other.
// More can be found [here](https://use.ink/macros-attributes/contract/).
#[ink::contract]
mod bulletin_board {

    use highlighted_posts::{
        HighlightedPostsError, HighlightedPostsRef, HIGHLIGHT_POST_SELECTOR,
    };

    use ink::{
        env::{
            call::{build_call, ExecutionInput, FromAccountId, Selector},
            DefaultEnvironment, Error as InkEnvError,
        },
        LangError,
    };

    use ink::{
        codegen::EmitEvent,
        prelude::{format, string::String, vec::Vec},
        reflect::ContractEventBase,
        storage::Mapping,
        ToAccountId,
    };
    /// Errors returned by the contract's methods.
    #[derive(Debug, PartialEq, Eq, scale::Encode, scale::Decode)]
    #[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]
    pub enum BulletinBoardError {
        /// There already exists a bulletin for the calling account.
        /// Only one bulletin per account is allowed.
        BulletinAlreadyExists,
        /// Bulletin not found.
        BulletinNotFound,
        /// Value transferred was too low to pay for the listing.
        /// Transfer `listing_cost` to pay for the post.
        ListingCostTooLow(u128),
        /// Error returned when interacting with the `HighlightedPosts`
        /// contract.
        // NOTE: This is a wrapper around an error returned from calling a
        // different contract.
        HighlightError(HighlightedPostsError),
        /// An interaction with ink! environment has failed
        // NOTE: We're representing the `ink::env::Error` as `String` b/c the
        // type does not have Encode/Decode implemented.
        InkEnvError(String),
    }

    impl From<HighlightedPostsError> for BulletinBoardError {
        fn from(e: HighlightedPostsError) -> Self {
            BulletinBoardError::HighlightError(e)
        }
    }

    impl From<InkEnvError> for BulletinBoardError {
        fn from(e: InkEnvError) -> Self {
            BulletinBoardError::InkEnvError(format!("{:?}", e))
        }
    }

    // Alias for wrapper around all events in this contract generated by ink!.
    type Event = <BulletinBoard as ContractEventBase>::Type;

    // We will be storing `Bulletin` as _value_ in our contract (value type in
    // `Mapping<K, Value>`) and for that reason we need to derive
    // `ink::storage::traits::StorageLayout` for `std` feature.
    // `Mapping::insert(k, v)` requires that there exists implementation of
    // `Storabe` for `v`'s type, it (`Storable`) has blanket implementation
    // for all types that implement `scale::Decode` and `scale::Encode`.
    #[derive(Debug, PartialEq, Eq, scale::Encode, scale::Decode)]
    #[cfg_attr(
        feature = "std",
        derive(scale_info::TypeInfo, ink::storage::traits::StorageLayout)
    )]
    pub struct Bulletin {
        author: AccountId,
        posted_at: BlockNumber,
        expires_at: BlockNumber,
        // NOTE: `String` type here is ink!'s wrapper for `Vec<u8>`.
        text: String,
    }

    /// Defines the storage of your contract.
    //
    // There must be exactly one `#[ink(storage)]` struct.
    #[ink(storage)]
    pub struct BulletinBoard {
        // Monotonically increasing counter for assigning unique IDs to
        // bulletins.
        id_counter: u32,
        id_map: Mapping<AccountId, u32>,
        bulletin_map: Mapping<u32, Bulletin>,
        post_authors: Vec<AccountId>,
        price_per_block_listing: u128,
        elements_count: u32,
        highlighted_posts_board: Option<AccountId>,
    }

    impl BulletinBoard {
        // Doc strings are added to the `metadata.json` file generated when
        // contract is built. Documentation can be then consumed by other
        // clients (UI clients). For more information see the [documentation](https://use.ink/metadata).
        //
        /// Creates an instance of the bulletin board contract.
        /// - `version` is the version of contract's  Works also as salt for
        ///   deployment of `highlighted_posts_board_hash` contract so when
        ///   `BulletinBoard::new` is called from the same account, use a
        ///   different `version` to re-instantiate it.
        /// - `price_per_block_listing` specifies the price of listing the
        /// post for every block.
        /// - `highlighted_posts_board` argument is a code hash of
        /// the contract we will instantiate.
        #[ink(constructor)]
        pub fn new(
            version: u8,
            price_per_block_listing: u128,
            highlighted_posts_board_hash: Hash
        ) -> Self {
            // The `*Ref` pattern allows for type-safe operation on the
            // contract. Here, we're constructing an instance of
            // `HighlightedPosts` contract.

            let highlighted_posts_board_ref = HighlightedPostsRef::new()
                .endowment(0) /* Amount of value transferred as part of the call. 
                               * It should not be required but the API of `*Ref` pattern 
                               * does not allow for calling `instantiate()` 
                               * on a builder where `endowment` is not set.*/
                .code_hash(highlighted_posts_board_hash)
                .salt_bytes(&[version.to_le_bytes().as_ref(), Self::env().caller().as_ref()].concat()[..4])
                .instantiate();

            // We're mapping back to the `AccountId` so that we can use it in
            // the `highlight_post` method down below.
            let highlighted_posts_board =
                <HighlightedPostsRef as ToAccountId<
                    super::bulletin_board::Environment,
                >>::to_account_id(&highlighted_posts_board_ref);

            Self {
                id_counter: 0,
                price_per_block_listing: price_per_block_listing,
                elements_count: 0,
                highlighted_posts_board: Some(highlighted_posts_board),
                post_authors: Vec::new(),
                bulletin_map: Mapping::default(),
                id_map: Mapping::default(),
            }
        }

        // Contracts can have multiple constructors. You can choose which to use
        // when instantiating a contract.
        /// Creates an instance of `BulletinBoard` contract where posting is
        /// "free".
        #[ink(constructor)]
        pub fn free() -> Self {
            Self {
                id_counter: 0,
                price_per_block_listing: 0,
                elements_count: 0,
                highlighted_posts_board: None,
                post_authors: Vec::new(),
                bulletin_map: Mapping::default(),
                id_map: Mapping::default(),
            }
        }

        /// Adds new post to the "bulletin board".
        /// Parameters of the post are:
        /// * `expires_after` - block number until which this post should be
        ///   considered valid.
        /// * `test` - text of the new post.
        /// Accepts a value (token) transfer if the post needs to be paid for.
        ///
        /// Fails if any of the following is true:
        /// * not enough tokens have been transferred to cover the cost of
        ///   posting,
        /// * there already exists a post from the caller's account.
        ///
        /// # Note
        ///
        /// The method needs to be annotated with `payable` - only then it is
        /// allowed to receive value as part of the call.
        #[ink(message, payable)]
        pub fn post(
            &mut self,
            expires_after: BlockNumber,
            text: String,
        ) -> Result<(), BulletinBoardError> {
            // There are over 20 methods available in `Self:env()` that give
            // contract access to the "blockchain context".
            let caller = Self::env().caller();

            // We can add `println!` statements that will be written to stdout
            // during the test.
            ink::env::debug_println!("`{:?}` wants to create a post that expires after `{:?}` blocks \
                with the text `{:?}`", caller, expires_after, text);

            if self.id_map.contains(&caller) {
                // Contract's methods can return `Result::Err` variant
                // so that the caller can handle it and recover. This does not
                // fail and rollback the transaction.
                return Err(BulletinBoardError::BulletinAlreadyExists);
            }

            // Check how much tokens have been transferred as part of the
            // transaction.
            let transferred_amount = self.env().transferred_value();

            let listing_cost = self
                .price_per_block_listing
                .checked_mul(expires_after as u128)
                .unwrap_or(u128::MAX);

            // Returning `Result::Err` reverts callee's state but makes it
            // simpler for the caller to handle an error - in contract to
            // `panic!` that doesn't contain any additional
            // information and is simply `CalleeTrapped`.
            if transferred_amount < listing_cost {
                return Err(BulletinBoardError::ListingCostTooLow(
                    listing_cost,
                ));
            }

            let curr_block_number = Self::env().block_number();
            let event =
                self._post(curr_block_number, expires_after, caller, text);

            // Only if user asked to highlight the post.
            if expires_after != 0 {
                self.highlight_post(event.author, event.id, listing_cost)?;
                self.reimburse(caller, transferred_amount - listing_cost);
            }
            Self::emit_event(Self::env(), Event::BulletinPosted(event));
            Ok(())
        }

        /// Deletes the post from the caller (if exists).
        #[ink(message)]
        pub fn delete(&mut self) -> Result<(), BulletinBoardError> {
            let author = Self::env().caller();
            let bulletin_id = self.delete_bulletin(author)?;
            match self.delete_highlight(author) {
                Ok(()) => {
                    Self::emit_event(
                        Self::env(),
                        Event::BulletinRemoved(BulletinRemoved {
                            author,
                            id: bulletin_id,
                        }),
                    );
                    Ok(())
                }
                Err(BulletinBoardError::HighlightError(
                    HighlightedPostsError::HighlightNotFound,
                )) => Ok(()),
                Err(err) => {
                    // It is fine if we don't find the bulletin on the
                    // highlighted posts board but other
                    // errors should be propagated upwards.
                    Err(err)
                }
            }
        }

        /// Returns the post created by the caller.
        #[ink(message)]
        pub fn get_by_account(
            &self,
            account_id: AccountId,
        ) -> Option<Bulletin> {
            self.get_value(&account_id)
        }

        /// Returns the post referenced by the ID of the bulletin.
        #[ink(message)]
        pub fn get_by_id(&self, id: u32) -> Option<Bulletin> {
            self.bulletin_map.get(&id)
        }

        /// Returns an address of `highlighted_posts` board contract
        #[ink(message)]
        pub fn get_highlights_board(&self) -> Option<AccountId> {
            self.highlighted_posts_board
        }

        // To terminate a contract means to delete it from the blockchain
        // storage. One can choose whether to transfer the contract's
        // balance to others, for example a caller.
        /// Terminates the contract, iff the board is empty, with the caller as
        /// beneficiary.
        #[ink(message)]
        pub fn teminate_contract(&mut self) {
            if self.elements_count == 0 {
                self.env().terminate_contract(self.env().caller());
            }
        }

        /// Returns a price for highlighting the post for 1 block.
        #[ink(message)]
        pub fn get_highlight_price_per_block(&self) -> u128 {
            self.price_per_block_listing
        }

        /// Returns all currently visible posts' authors.
        #[ink(message)]
        pub fn get_posts_authors(&self) -> Vec<AccountId> {
            self.post_authors.clone()
        }

        /// Reimburses the caller with overpaid tokens.
        /// Panics if the transfer fails - this means this contract's balance is
        /// too low which means something went wrong.
        fn reimburse(&self, recipient: AccountId, amount: u128) {
            if Self::env().transfer(recipient, amount).is_err() {
                panic!("failed to reimburse the caller")
            }
        }

        // Private method that doesn't need to interact with the "blockchain
        // env". Useful for testing where there's a layer of a logic
        // that can't be easily mocked.
        fn insert_bulletin(
            &mut self,
            caller: &AccountId,
            bulletin: Bulletin,
        ) -> u32 {
            let bulletin_id = self.id_counter;
            self.id_map.insert(caller, &bulletin_id);
            self.bulletin_map.insert(bulletin_id, &bulletin);
            self.id_counter = bulletin_id + 1;
            self.post_authors.push(caller.clone());
            bulletin_id
        }

        fn get_value(&self, caller: &AccountId) -> Option<Bulletin> {
            if let Some(bulletin_id) = self.id_map.get(caller) {
                let bulletin = self.bulletin_map.get(bulletin_id).unwrap_or_else(|| {
                    // Contracts can also panic - this WILL fail and rollback the
                    // transaction. Caller can still handle it and
                    // recover but there will be no additional information about the error available. 
                    // Use when you know something *unexpected* happened.
                    panic!(
                        "broken invariant: expected entry to exist for the caller"
                    )
                });
                Some(bulletin)
            } else {
                None
            }
        }

        fn delete_bulletin(
            &mut self,
            caller: AccountId,
        ) -> Result<u32, BulletinBoardError> {
            match self.id_map.get(caller) {
                None => return Err(BulletinBoardError::BulletinNotFound),
                Some(bulletin_id) => {
                    self.bulletin_map.remove(bulletin_id);
                    self.id_map.remove(caller);
                    self.elements_count -= 1;
                    self.post_authors.retain(|author| author != &caller);
                    Ok(bulletin_id)
                }
            }
        }

        fn _post(
            &mut self,
            curr_block: BlockNumber,
            expires_after: BlockNumber,
            author: AccountId,
            text: String,
        ) -> BulletinPosted {
            let expires_at = curr_block + expires_after;

            let bulletin = Bulletin {
                author,
                posted_at: curr_block,
                expires_at,
                text,
            };
            let bulletin_id = self.insert_bulletin(&author, bulletin);
            self.elements_count += 1;
            BulletinPosted {
                author,
                expires_at,
                id: bulletin_id,
            }
        }

        /// Calls the `HighlightsBoard` contract to highlight the post by
        /// `author`.
        // Constructs the cross-contract call using the manual builder pattern.
        //
        // It's more verbose than the `*Ref` pattern and we need to be more
        // careful to use proper types.
        fn highlight_post(
            &self,
            author: AccountId,
            id: u32,
            cost: u128,
        ) -> Result<(), BulletinBoardError> {
            if let Some(highlight_board) = self.highlighted_posts_board {
                // The potential call result here is a three layers of `Result`,
                // where each layer has a different error. We're
                // handling each explicitly below, for the example purposes, but
                // you can also choose to short-circuit with `?`.
                let call_result: Result<Result<(), HighlightedPostsError>, ink::LangError> = build_call::<DefaultEnvironment>()
                    .call(highlight_board) // Address of the contract we want to call
                    .exec_input(
                        ExecutionInput::new(Selector::new(
                            HIGHLIGHT_POST_SELECTOR, /* Selector tells ink!
                                                      * which method on that
                                                      * contract to call */
                        ))
                        .push_arg(author) // Pass in arguments of the method.
                        .push_arg(id),
                    )
                    .transferred_value(cost) // We can transfer tokens forward to another contract.
                    .returns::<Result<Result<(), HighlightedPostsError>, LangError>>()
                    .invoke();

                match call_result {
                    // An error emitted by the smart contracting language.
                    // For more details see ink::LangError.
                    Err(lang_error) => {
                        panic!("Unexpected ink::LangError: {:?}", lang_error)
                    }
                    // `Result<(), HighlightedPostsError>` is the return type of
                    // the method we're calling.
                    Ok(Err(contract_call_error)) => {
                        return Err(BulletinBoardError::from(
                            contract_call_error,
                        ))
                    }
                    Ok(Ok(_unit)) => return Ok(()),
                }
            }
            Ok(())
        }

        // Constructs the cross-contract call using the `*Ref` pattern.
        // More type-safe than the manual builder pattern. If you expanded the
        // `#[ink::contract]` macro for this contract, you will find
        // that `from_account_id` function constructs the `build_call` just like
        // we did manually in `fn highlight_post`.
        //
        // NOTE: Currently `*Ref` wrapper does not support transferring tokens,
        // unlike the builder pattern with `transferred_value` method
        // and that's why `highlight_post` uses the builder pattern.
        fn delete_highlight(
            &self,
            author: AccountId,
        ) -> Result<(), BulletinBoardError> {
            if let Some(highlight_board) = self.highlighted_posts_board {
                <HighlightedPostsRef as FromAccountId<
                    super::bulletin_board::Environment,
                >>::from_account_id(highlight_board)
                .delete_by_author(author)?
            }
            Ok(())
        }

        // As soon as another contract that emits events is introduced as
        // dependency, see `highlighted_posts` in `Cargo.toml`,
        // compilation fails as it can't resolve which event is going to be
        // returned from the contract.
        // To verify, replace calls to `Self::emit_event` with
        // `self::env().emit_event(_)`.
        fn emit_event<EE>(emitter: EE, event: Event)
        where
            EE: EmitEvent<BulletinBoard>,
        {
            emitter.emit_event(event);
        }
    }

    /// Defines an event that is emitted every time value is incremented.
    #[ink(event)]
    pub struct BulletinPosted {
        // `topic` tag allows simplifies lookup of the events.
        // If you mark field as `topic` it will be indexed.
        //
        // If you don't want event to be indexed, see [`#[ink(anonymous)]`](https://use.ink/macros-attributes/anonymous/).
        #[ink(topic)]
        author: AccountId,
        expires_at: BlockNumber,
        id: u32,
    }

    #[ink(event)]
    pub struct BulletinRemoved {
        #[ink(topic)]
        author: AccountId,
        id: u32,
    }
    /// Unit tests in Rust are normally defined within such a `#[cfg(test)]`
    /// module and test functions are marked with a `#[test]` attribute.
    /// The below code is technically just normal Rust code.
    #[cfg(test)]
    mod tests {
        /// Imports all the definitions from the outer scope so we can use
        /// them here.
        use super::*;

        use ink::env::test::{
            default_accounts, get_account_balance, recorded_events,
            DefaultAccounts, EmittedEvent,
        };
        use scale::Decode;

        // Returns accounts that are pre-seeded in the test database.
        // We can use them as authors for transactions.
        fn get_default_test_accounts(
        ) -> DefaultAccounts<ink::env::DefaultEnvironment> {
            default_accounts::<ink::env::DefaultEnvironment>()
        }

        // Returns balance of test account.
        fn get_balance(account_id: AccountId) -> Balance {
            get_account_balance::<ink::env::DefaultEnvironment>(account_id)
                .expect("Cannot get account balance")
        }

        // Sets caller returned by the next `Self::env().caller()` method call
        // in the contract.
        fn set_caller(caller: AccountId) {
            ink::env::test::set_caller::<ink::env::DefaultEnvironment>(caller);
        }

        const PRICE_PER_BLOCK_COST: u128 = 10;

        #[test]
        fn constructor_works() {
            // let instance = BulletinBoard::new(PRICE_PER_BLOCK_COST);
            // assert_eq!(price_per_block_listing,
            // PRICE_PER_BLOCK_COST);

            let default = BulletinBoard::free();
            assert_eq!(default.price_per_block_listing, 0);
        }

        #[ink::test]
        fn post_free_succeeds() {
            let accounts = get_default_test_accounts();
            let alice = accounts.alice;
            let mut instance = BulletinBoard::free();
            let expire_after: BlockNumber = 100;
            let text: ink::prelude::string::String = "Text".into();
            // Setting Alice as the first caller is not strictly required as
            // it's the default for ink tests. We do it for clarity
            // though.
            set_caller(alice);
            assert!(
                instance.post(expire_after, text.clone()).is_ok(),
                "posting was expected to succeed"
            );
            let expected_bulletin = Bulletin {
                author: alice,
                posted_at: 0,
                expires_at: 100,
                text,
            };
            assert_eq!(
                instance.get_by_id(0).expect("to find bulletin"),
                expected_bulletin
            );
            assert_eq!(
                instance.get_by_account(alice).expect("to find bulletin"),
                expected_bulletin
            );
            let frank = accounts.frank;
            assert!(
                instance.get_by_account(frank).is_none(),
                "There should be no posts from Frank"
            );
        }

        #[ink::test]
        fn event_on_post() {
            let mut instance = BulletinBoard::free();
            let bulletin = post_from_alice(&mut instance);
            // We can verify that the proper events have been emitted during the
            // call.
            let recorded_events = recorded_events().collect::<Vec<_>>();
            assert_expected_post_event(
                &recorded_events[0],
                bulletin.author,
                bulletin.expires_at,
                0,
            );
        }

        fn assert_expected_post_event(
            event: &EmittedEvent,
            expected_author: AccountId,
            expires_at_block: BlockNumber,
            expected_id: u32,
        ) {
            let decoded_event = <Event as Decode>::decode(&mut &event.data[..])
                .expect("encountered invalid contract event data buffer");
            if let Event::BulletinPosted(BulletinPosted {
                author,
                expires_at,
                id,
            }) = decoded_event
            {
                assert_eq!(author, expected_author);
                assert_eq!(expires_at, expires_at_block);
                assert_eq!(id, expected_id);
            } else {
                panic!("encountered unexpected event kind: expected `BulletinPosted`")
            };
        }

        fn post_from_alice(instance: &mut BulletinBoard) -> Bulletin {
            let accounts = get_default_test_accounts();
            let alice = accounts.alice;
            let expire_after: BlockNumber = 100;
            let text: ink::prelude::string::String = "Text".into();
            let expected_bulletin = Bulletin {
                author: alice,
                posted_at: 0,
                expires_at: 100,
                text: text.clone(),
            };
            set_caller(alice);
            assert!(
                instance.post(expire_after, text).is_ok(),
                "posting was expected to succeed"
            );
            expected_bulletin
        }

        #[ink::test]
        fn delete_works() {
            let accounts = get_default_test_accounts();
            let alice = accounts.alice;
            let mut instance = BulletinBoard::free();
            assert!(
                matches!(
                    instance.delete(),
                    Result::Err(BulletinBoardError::BulletinNotFound)
                ),
                "no posts from Alice expected to be found on the board"
            );
            let alice_bulletin = post_from_alice(&mut instance);
            assert_eq!(
                instance.get_by_account(alice).unwrap(),
                alice_bulletin,
                "Bulletin was expected to be found after posting"
            );
            set_caller(accounts.frank);
            assert!(
                matches!(
                    instance.delete(),
                    Result::Err(BulletinBoardError::BulletinNotFound)
                ),
                "no posts from Frank"
            );
            set_caller(accounts.alice);
            assert!(instance.delete().is_ok(), "deletion should succeed");
            assert!(
                matches!(
                    instance.delete(),
                    Result::Err(BulletinBoardError::BulletinNotFound)
                ),
                "second deletion should return an error"
            );
            assert!(
                instance.get_by_account(alice).is_none(),
                "expected no posts after deleting"
            );
        }

        #[ink::test]
        fn event_on_delete() {
            let mut instance = BulletinBoard::free();
            let bulletin = post_from_alice(&mut instance);
            assert!(instance.delete().is_ok(), "deletion should succeed");
            let recorded_events = recorded_events().collect::<Vec<_>>();
            assert_expected_post_event(
                &recorded_events[0],
                bulletin.author,
                bulletin.expires_at,
                0,
            );
            // The events returned by `recored_events()` are all events emitted
            // since the beginning of the test.
            // The first event (at index 0) will be `BulletinPosted` by Alice
            // from the couple lines back.
            // The second event (at index 1) will be the `BulletinRemoved`
            // event.
            assert_bulletin_removed_event(
                &recorded_events[1],
                get_default_test_accounts().alice,
                0,
            );
        }

        fn assert_bulletin_removed_event(
            event: &EmittedEvent,
            expected_author: AccountId,
            expected_id: u32,
        ) {
            let decoded_event = <Event as Decode>::decode(&mut &event.data[..])
                .expect("encountered invalid contract event data buffer");
            if let Event::BulletinRemoved(BulletinRemoved { author, id }) =
                decoded_event
            {
                assert_eq!(author, expected_author);
                assert_eq!(id, expected_id);
            } else {
                panic!("encountered unexpected event kind: expected `BulletinRemoved`")
            }
        }
    }
}
