build-all:
	cargo +nightly-2023-02-07 contract build --release --manifest-path highlighted_posts/Cargo.toml
	cargo +nightly-2023-02-07 contract build --release --manifest-path bulletin_board/Cargo.toml
